version: '3.8'

networks:
  aqm:
    name: aqm
    ipam:
      driver: default
      config:
        - subnet: 10.0.100.0/24

services:
  kafka_zk:
    build:
      context: kafka/
      dockerfile: Dockerfile
    container_name: kafkaZK
    environment:
      KAFKA_ACTION: start-zk
    networks:
      aqm:
        ipv4_address: 10.0.100.22
    ports:
      - "2181:2181"

  kafka_server:
    build:
      context: kafka/
      dockerfile: Dockerfile
    environment:
      - KAFKA_ACTION=start-kafka
    container_name: kafkaServer
    networks:
      aqm:
        ipv4_address: 10.0.100.23
    ports:
      - "9092:9092"

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.0.100.23:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=10.0.100.22:2181
    container_name: kafkaUI
    networks:
      aqm:
    ports:
      - "8080:8080"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    hostname: logstash
    container_name: logstash
    volumes:
      - ./logstash/pipeline/from_python_to_kafka.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ENABLED=false
    networks:
      aqm:
  
  ingestion_manager:
    build:
      context: ingestion_manager
      dockerfile: Dockerfile
    hostname: ingestion_manager
    container_name: ingestion_manager
    depends_on:
      - logstash
    networks:
      aqm:

  # spark:
  #   build: 
  #     context: spark
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4040:4040
  #   container_name: spark
  #   depends_on: 
  #       - kafkaServer