version: '3.8'

networks:
  tap:
    name: tap
    external: true

services:
  kafka_zk:
    build:
      context: kafka/
      dockerfile: Dockerfile
    container_name: kafkaZK
    environment:
      KAFKA_ACTION: start-zk
    networks:
      tap:
        ipv4_address: 10.0.100.22
    ports:
      - "2181:2181"

  kafka_server:
    build:
      context: kafka/
      dockerfile: Dockerfile
    environment:
      - KAFKA_ACTION=start-kafka
    container_name: kafkaServer
    networks:
      tap:
        ipv4_address: 10.0.100.23
    ports:
      - "9092:9092"

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.0.100.23:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=10.0.100.22:2181
    container_name: KafkaUI
    networks:
      tap:
    ports:
      - "8080:8080"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    hostname: logstash
    container_name: logstash
    volumes:
      - ./logstash/pipeline/from_python_to_kafka.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ENABLED=false
    networks:
      - tap
  
  ingestion_manager:
    image: python:3.10-slim
    hostname: ingestion_manager
    container_name: ingestion_manager
    environment:
      - API_KEY=0e72cb61-87b6-4ab4-b422-0886e1305ac6
      - COUNTRY_NAME=Italy
      - STATE_NAME=Sicily
      - GPS_LAT=37.500000
      - GPS_LON=15.090278
      - CITY_TO_SCAN=San Filippo del Mela
      - DATA_ACTION=NEAREST_GPS_CITY
    depends_on:
      - logstash
    working_dir: /ingestion-manager
    networks:
      - tap
    volumes:
      - ./ingestion_manager/:/ingestion-manager
    command: ["sh", "-c", "pip3 install --no-cache-dir --disable-pip-version-check -r requirements.txt && python3 ingestion_manager.py"]